; /conf/www.conf

[www]
; 実行するユーザーとグループ
user = www-data
group = www-data

; UNIXドメインソケットから、TCPの9000番ポートでの待ち受けに変更
listen = 9000

; NGINXが9000番にアクセスしてくるのを許可する（TCP接続ではいらないらしい）
listen.owner = www-data
listen.group = www-data

; 環境変数をDockerからPHPに引き継げるようにする
clear_env = no
